query GetWatchlistCoins {
  watchlistCoins {
    id
    marketCoin {
      id
    }
  }
}

query GetWatchlistCoinQuery ($id: ID!) {
  watchlistCoin(id: $id) {
    id
    marketCoin {
      id
    }
  }
}
