query IndexBaseCurrencies {
  baseCurrencies {
    id
    code
    fullName
    exchangeRate
    symbol
  }
}

query ShowBaseCurrency {
 baseCurrency(id: $id) {
  id
  code
  fullName
  exchangeRate
  symbol
  }
}

