## Queries

query IndexMarketCoins {
 marketCoins {
    ...AllAttributesForCoins
  }
}

query ShowMarketCoin ($id: ID!) {
 marketCoin(id: $id) {
    ...AllAttributesForCoins
  }
}

## Fragments

fragment AllAttributesForCoins on MarketCoin {
  id
  code
  symbol
  name
  coinName
  fullName
  logoUrl
  algorithm
  proofType
  marketCap
  price
  dayOpen
  dayHigh
  dayLow
  priceVariation
  dayHighVariation
  dayLowVariation
  allTimeHigh
  rank
  createdAt
  updatedAt
}
