## Queries
query IndexPortfolioCoins {
 portfolioCoins {
    ...AllAttributes
  }
}

query ShowPortfolioCoin ($id: ID!) {
 portfolioCoin(id: $id) {
    ...AllAttributes
  }
}

# TODO : find a solution to import AllAttributesForCoins
fragment AllAttributes on PortfolioCoin {
  quantity

  marketCoin {
    ...AllAttributesForCoins # TODO: to change
  }
  userPortfolio {
    id
  }
}

fragment AllAttributesForCoins on MarketCoin {
  id
  code
  symbol
  name
  coinName
  fullName
  logoUrl
  algorithm
  proofType
  marketCap
  price
  dayOpen
  dayHigh
  dayLow
  priceVariation
  dayHighVariation
  dayLowVariation
  allTimeHigh
  rank
  createdAt
  updatedAt
}
