## Queries

query IndexPortfolioCoins {
 portfolioCoins {
    ...AllAttributes
  }
}

query ShowPortfolioCoin ($id: ID!) {
 portfolioCoin(id: $id) {
    ...AllAttributes
  }
}

fragment AllAttributes on PortfolioCoin {
  quantity

  marketCoin {
    id
  }
  userPortfolio {
    id
  }
}
