## Queries

query ShowUserSetting {
  userSetting {
    id
    weather

    primaryMarketCoin {
      id
      code
      symbol
      name
      coinName
      fullName
      marketCap
      price
      dayOpen
      dayHigh
      dayLow
      priceVariation
      dayHighVariation
      dayLowVariation
    }

    baseCurrency {
      id
      code
      exchangeRate
      symbol
    }
  }
}
