## Queries

query ShowCurrentUser {
  currentUser {
    id
    email
    role

    userSetting {
      id
    }
    userPortfolio {
      id
    }
    userWatchlist {
      id
    }

    ...PrivateAttributes
    ...Timestamps
  }
}

## Mutations

mutation CreateAnonymousUser {
  createAnonymousUser {
    token
  }
}

## Fragments

fragment PrivateAttributes on User {
  token
}

fragment Timestamps on User {
  updatedAt
  createdAt
}
