## Queries

query GetCurrentUser {
  currentUser {
    id
    email
    ...PrivateAttributes
    ...Timestamps
  }
}

## Mutations

#mutation Authenticate($idToken: String!) {
#  authenticate(idToken: $idToken) {
#    name
#    email
#  }
#}

mutation CreateAnonymousUser {
  createAnonymousUser {
    token
  }
}

# signinUser(email: {
#    email: $email,
#    password: $password
#  }) {
#    token
#    user {
#      id
#    }
#  }
#}

## Fragments

fragment PrivateAttributes on User {
  token
}

fragment Timestamps on User {
  updatedAt
  createdAt
}
