## Queries

query IndexWatchlistCoins {
  watchlistCoins {
    ...AllAttributes
  }
}

query ShowWatchlistCoin ($id: ID!) {
  watchlistCoin(id: $id) {
    ...AllAttributes
  }
}

fragment AllAttributes on WatchlistCoin {
  id

  marketCoin {
    id
  }
  userWatchlist {
    id
  }
}
